version: '3'

services:
    aeropoint:
        image: aeropoint
        build: .
        volumes:
            - ${PWD}/output:/root/src/output
            - ${PWD}/rawData:/root/src/rawData
        ports:
            - "21:21"

    aeropointtests:
        image: aeropoint
        build: .
