version: '3'

services:
    aeropoint:
        image: aeropoint
        build: .
        volumes:
            - ${PWD}/output:/root/src/output
            - ${PWD}/rawData:/root/src/rawData

    aeropointtests:
        image: aeropoint
        build: .
